// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.1
// source: protobuf/command.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Commands struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commands []*Command `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
}

func (x *Commands) Reset() {
	*x = Commands{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_command_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Commands) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commands) ProtoMessage() {}

func (x *Commands) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_command_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commands.ProtoReflect.Descriptor instead.
func (*Commands) Descriptor() ([]byte, []int) {
	return file_protobuf_command_proto_rawDescGZIP(), []int{0}
}

func (x *Commands) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

// a message that server can send to clients
type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Command:
	//	*Command_TickCommand
	//	*Command_IdCommand
	//	*Command_WriterCommand
	Command isCommand_Command `protobuf_oneof:"command"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_command_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_command_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_protobuf_command_proto_rawDescGZIP(), []int{1}
}

func (m *Command) GetCommand() isCommand_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (x *Command) GetTickCommand() *TickCommand {
	if x, ok := x.GetCommand().(*Command_TickCommand); ok {
		return x.TickCommand
	}
	return nil
}

func (x *Command) GetIdCommand() *IdCommand {
	if x, ok := x.GetCommand().(*Command_IdCommand); ok {
		return x.IdCommand
	}
	return nil
}

func (x *Command) GetWriterCommand() *WriterCommand {
	if x, ok := x.GetCommand().(*Command_WriterCommand); ok {
		return x.WriterCommand
	}
	return nil
}

type isCommand_Command interface {
	isCommand_Command()
}

type Command_TickCommand struct {
	TickCommand *TickCommand `protobuf:"bytes,1,opt,name=tick_command,json=tickCommand,proto3,oneof"`
}

type Command_IdCommand struct {
	IdCommand *IdCommand `protobuf:"bytes,2,opt,name=id_command,json=idCommand,proto3,oneof"`
}

type Command_WriterCommand struct {
	WriterCommand *WriterCommand `protobuf:"bytes,3,opt,name=writer_command,json=writerCommand,proto3,oneof"`
}

func (*Command_TickCommand) isCommand_Command() {}

func (*Command_IdCommand) isCommand_Command() {}

func (*Command_WriterCommand) isCommand_Command() {}

//* A time update, representing a unit time has passed.
type TickCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RandomSeed []byte `protobuf:"bytes,1,opt,name=random_seed,json=randomSeed,proto3" json:"random_seed,omitempty"`
}

func (x *TickCommand) Reset() {
	*x = TickCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_command_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TickCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickCommand) ProtoMessage() {}

func (x *TickCommand) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_command_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickCommand.ProtoReflect.Descriptor instead.
func (*TickCommand) Descriptor() ([]byte, []int) {
	return file_protobuf_command_proto_rawDescGZIP(), []int{2}
}

func (x *TickCommand) GetRandomSeed() []byte {
	if x != nil {
		return x.RandomSeed
	}
	return nil
}

//*
// Client has connected or disconnected or changed id.
type IdCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//* Id that has been removed. If empty, it means a new client id has joined.
	OldId string `protobuf:"bytes,1,opt,name=old_id,json=oldId,proto3" json:"old_id,omitempty"`
	//* Id that has been added. If empty, it means a client has disconnected.
	NewId string `protobuf:"bytes,2,opt,name=new_id,json=newId,proto3" json:"new_id,omitempty"`
}

func (x *IdCommand) Reset() {
	*x = IdCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_command_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdCommand) ProtoMessage() {}

func (x *IdCommand) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_command_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdCommand.ProtoReflect.Descriptor instead.
func (*IdCommand) Descriptor() ([]byte, []int) {
	return file_protobuf_command_proto_rawDescGZIP(), []int{3}
}

func (x *IdCommand) GetOldId() string {
	if x != nil {
		return x.OldId
	}
	return ""
}

func (x *IdCommand) GetNewId() string {
	if x != nil {
		return x.NewId
	}
	return ""
}

//*
// Broadcast of a message from a client.
type WriterCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//* Id of client
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	//* Custom message sent by a client.
	Command []byte `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
}

func (x *WriterCommand) Reset() {
	*x = WriterCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_command_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriterCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriterCommand) ProtoMessage() {}

func (x *WriterCommand) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_command_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriterCommand.ProtoReflect.Descriptor instead.
func (*WriterCommand) Descriptor() ([]byte, []int) {
	return file_protobuf_command_proto_rawDescGZIP(), []int{4}
}

func (x *WriterCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WriterCommand) GetCommand() []byte {
	if x != nil {
		return x.Command
	}
	return nil
}

type StandAloneRoomServerSetting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Port        int32        `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	RoomSetting *RoomSetting `protobuf:"bytes,2,opt,name=room_setting,json=roomSetting,proto3" json:"room_setting,omitempty"`
	BackupFile  string       `protobuf:"bytes,3,opt,name=backup_file,json=backupFile,proto3" json:"backup_file,omitempty"`
}

func (x *StandAloneRoomServerSetting) Reset() {
	*x = StandAloneRoomServerSetting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_command_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StandAloneRoomServerSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandAloneRoomServerSetting) ProtoMessage() {}

func (x *StandAloneRoomServerSetting) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_command_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandAloneRoomServerSetting.ProtoReflect.Descriptor instead.
func (*StandAloneRoomServerSetting) Descriptor() ([]byte, []int) {
	return file_protobuf_command_proto_rawDescGZIP(), []int{5}
}

func (x *StandAloneRoomServerSetting) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *StandAloneRoomServerSetting) GetRoomSetting() *RoomSetting {
	if x != nil {
		return x.RoomSetting
	}
	return nil
}

func (x *StandAloneRoomServerSetting) GetBackupFile() string {
	if x != nil {
		return x.BackupFile
	}
	return ""
}

type CreateRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId           string       `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoomSetting      *RoomSetting `protobuf:"bytes,2,opt,name=room_setting,json=roomSetting,proto3" json:"room_setting,omitempty"`
	ShortDescription string       `protobuf:"bytes,3,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_command_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_command_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_command_proto_rawDescGZIP(), []int{6}
}

func (x *CreateRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CreateRoomRequest) GetRoomSetting() *RoomSetting {
	if x != nil {
		return x.RoomSetting
	}
	return nil
}

func (x *CreateRoomRequest) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_command_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_command_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_command_proto_rawDescGZIP(), []int{7}
}

type DeleteRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *DeleteRoomRequest) Reset() {
	*x = DeleteRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_command_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoomRequest) ProtoMessage() {}

func (x *DeleteRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_command_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoomRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoomRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_command_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type DeleteRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteRoomResponse) Reset() {
	*x = DeleteRoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_command_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoomResponse) ProtoMessage() {}

func (x *DeleteRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_command_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoomResponse.ProtoReflect.Descriptor instead.
func (*DeleteRoomResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_command_proto_rawDescGZIP(), []int{9}
}

type ListRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListRoomRequest) Reset() {
	*x = ListRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_command_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomRequest) ProtoMessage() {}

func (x *ListRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_command_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomRequest.ProtoReflect.Descriptor instead.
func (*ListRoomRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_command_proto_rawDescGZIP(), []int{10}
}

type ListRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rooms []*RoomSummary `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
}

func (x *ListRoomResponse) Reset() {
	*x = ListRoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_command_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomResponse) ProtoMessage() {}

func (x *ListRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_command_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomResponse.ProtoReflect.Descriptor instead.
func (*ListRoomResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_command_proto_rawDescGZIP(), []int{11}
}

func (x *ListRoomResponse) GetRooms() []*RoomSummary {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type RoomSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string                      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Setting          *RoomSetting                `protobuf:"bytes,2,opt,name=setting,proto3" json:"setting,omitempty"`
	ShortDescription string                      `protobuf:"bytes,3,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	HistorySummary   *RoomSummary_HistorySummary `protobuf:"bytes,4,opt,name=history_summary,json=historySummary,proto3" json:"history_summary,omitempty"`
}

func (x *RoomSummary) Reset() {
	*x = RoomSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_command_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomSummary) ProtoMessage() {}

func (x *RoomSummary) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_command_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomSummary.ProtoReflect.Descriptor instead.
func (*RoomSummary) Descriptor() ([]byte, []int) {
	return file_protobuf_command_proto_rawDescGZIP(), []int{12}
}

func (x *RoomSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoomSummary) GetSetting() *RoomSetting {
	if x != nil {
		return x.Setting
	}
	return nil
}

func (x *RoomSummary) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *RoomSummary) GetHistorySummary() *RoomSummary_HistorySummary {
	if x != nil {
		return x.HistorySummary
	}
	return nil
}

type DebugRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	B   []byte `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	S   string `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
	I32 uint32 `protobuf:"varint,3,opt,name=i32,proto3" json:"i32,omitempty"`
	I64 uint64 `protobuf:"varint,4,opt,name=i64,proto3" json:"i64,omitempty"`
	// Types that are assignable to Oo:
	//	*DebugRequest_Oi32
	//	*DebugRequest_Oi64
	Oo isDebugRequest_Oo `protobuf_oneof:"oo"`
}

func (x *DebugRequest) Reset() {
	*x = DebugRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_command_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DebugRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugRequest) ProtoMessage() {}

func (x *DebugRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_command_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugRequest.ProtoReflect.Descriptor instead.
func (*DebugRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_command_proto_rawDescGZIP(), []int{13}
}

func (x *DebugRequest) GetB() []byte {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *DebugRequest) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

func (x *DebugRequest) GetI32() uint32 {
	if x != nil {
		return x.I32
	}
	return 0
}

func (x *DebugRequest) GetI64() uint64 {
	if x != nil {
		return x.I64
	}
	return 0
}

func (m *DebugRequest) GetOo() isDebugRequest_Oo {
	if m != nil {
		return m.Oo
	}
	return nil
}

func (x *DebugRequest) GetOi32() uint32 {
	if x, ok := x.GetOo().(*DebugRequest_Oi32); ok {
		return x.Oi32
	}
	return 0
}

func (x *DebugRequest) GetOi64() uint64 {
	if x, ok := x.GetOo().(*DebugRequest_Oi64); ok {
		return x.Oi64
	}
	return 0
}

type isDebugRequest_Oo interface {
	isDebugRequest_Oo()
}

type DebugRequest_Oi32 struct {
	Oi32 uint32 `protobuf:"varint,5,opt,name=oi32,proto3,oneof"`
}

type DebugRequest_Oi64 struct {
	Oi64 uint64 `protobuf:"varint,6,opt,name=oi64,proto3,oneof"`
}

func (*DebugRequest_Oi32) isDebugRequest_Oo() {}

func (*DebugRequest_Oi64) isDebugRequest_Oo() {}

type DebugResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	B   []byte `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	S   string `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
	I32 uint32 `protobuf:"varint,3,opt,name=i32,proto3" json:"i32,omitempty"`
	I64 uint64 `protobuf:"varint,4,opt,name=i64,proto3" json:"i64,omitempty"`
	// Types that are assignable to Oo:
	//	*DebugResponse_Oi32
	//	*DebugResponse_Oi64
	Oo isDebugResponse_Oo `protobuf_oneof:"oo"`
}

func (x *DebugResponse) Reset() {
	*x = DebugResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_command_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DebugResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugResponse) ProtoMessage() {}

func (x *DebugResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_command_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugResponse.ProtoReflect.Descriptor instead.
func (*DebugResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_command_proto_rawDescGZIP(), []int{14}
}

func (x *DebugResponse) GetB() []byte {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *DebugResponse) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

func (x *DebugResponse) GetI32() uint32 {
	if x != nil {
		return x.I32
	}
	return 0
}

func (x *DebugResponse) GetI64() uint64 {
	if x != nil {
		return x.I64
	}
	return 0
}

func (m *DebugResponse) GetOo() isDebugResponse_Oo {
	if m != nil {
		return m.Oo
	}
	return nil
}

func (x *DebugResponse) GetOi32() uint32 {
	if x, ok := x.GetOo().(*DebugResponse_Oi32); ok {
		return x.Oi32
	}
	return 0
}

func (x *DebugResponse) GetOi64() uint64 {
	if x, ok := x.GetOo().(*DebugResponse_Oi64); ok {
		return x.Oi64
	}
	return 0
}

type isDebugResponse_Oo interface {
	isDebugResponse_Oo()
}

type DebugResponse_Oi32 struct {
	Oi32 uint32 `protobuf:"varint,5,opt,name=oi32,proto3,oneof"`
}

type DebugResponse_Oi64 struct {
	Oi64 uint64 `protobuf:"varint,6,opt,name=oi64,proto3,oneof"`
}

func (*DebugResponse_Oi32) isDebugResponse_Oo() {}

func (*DebugResponse_Oi64) isDebugResponse_Oo() {}

// Minimal info needed to control server's behavior.
type RoomSetting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tick      *TickSetting      `protobuf:"bytes,1,opt,name=tick,proto3" json:"tick,omitempty"`
	EndOfLife *EndOfLifeSetting `protobuf:"bytes,2,opt,name=end_of_life,json=endOfLife,proto3" json:"end_of_life,omitempty"`
}

func (x *RoomSetting) Reset() {
	*x = RoomSetting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_command_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomSetting) ProtoMessage() {}

func (x *RoomSetting) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_command_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomSetting.ProtoReflect.Descriptor instead.
func (*RoomSetting) Descriptor() ([]byte, []int) {
	return file_protobuf_command_proto_rawDescGZIP(), []int{15}
}

func (x *RoomSetting) GetTick() *TickSetting {
	if x != nil {
		return x.Tick
	}
	return nil
}

func (x *RoomSetting) GetEndOfLife() *EndOfLifeSetting {
	if x != nil {
		return x.EndOfLife
	}
	return nil
}

// How server should send TickCommand
type TickSetting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// number of bytes in random_seed in TickCommand
	Size                 uint32 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	FrequencyNanoseconds uint64 `protobuf:"varint,2,opt,name=frequency_nanoseconds,json=frequencyNanoseconds,proto3" json:"frequency_nanoseconds,omitempty"`
	// if
	AlwaysActive bool `protobuf:"varint,3,opt,name=always_active,json=alwaysActive,proto3" json:"always_active,omitempty"`
}

func (x *TickSetting) Reset() {
	*x = TickSetting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_command_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TickSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickSetting) ProtoMessage() {}

func (x *TickSetting) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_command_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickSetting.ProtoReflect.Descriptor instead.
func (*TickSetting) Descriptor() ([]byte, []int) {
	return file_protobuf_command_proto_rawDescGZIP(), []int{16}
}

func (x *TickSetting) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *TickSetting) GetFrequencyNanoseconds() uint64 {
	if x != nil {
		return x.FrequencyNanoseconds
	}
	return 0
}

func (x *TickSetting) GetAlwaysActive() bool {
	if x != nil {
		return x.AlwaysActive
	}
	return false
}

// When server should stop
type EndOfLifeSetting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Stop after n nanoseconds, never stop if equals 0
	MaxDuration uint64 `protobuf:"varint,1,opt,name=max_duration,json=maxDuration,proto3" json:"max_duration,omitempty"`
	// Stop after n nanoseconds without user message or user join, never stop if equals 0
	MaxDurationWhileIdle uint64 `protobuf:"varint,2,opt,name=max_duration_while_idle,json=maxDurationWhileIdle,proto3" json:"max_duration_while_idle,omitempty"`
	// Stop after all writer disconnected.
	CloseWhenAllWriterDisconnected bool `protobuf:"varint,3,opt,name=close_when_all_writer_disconnected,json=closeWhenAllWriterDisconnected,proto3" json:"close_when_all_writer_disconnected,omitempty"`
}

func (x *EndOfLifeSetting) Reset() {
	*x = EndOfLifeSetting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_command_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndOfLifeSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndOfLifeSetting) ProtoMessage() {}

func (x *EndOfLifeSetting) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_command_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndOfLifeSetting.ProtoReflect.Descriptor instead.
func (*EndOfLifeSetting) Descriptor() ([]byte, []int) {
	return file_protobuf_command_proto_rawDescGZIP(), []int{17}
}

func (x *EndOfLifeSetting) GetMaxDuration() uint64 {
	if x != nil {
		return x.MaxDuration
	}
	return 0
}

func (x *EndOfLifeSetting) GetMaxDurationWhileIdle() uint64 {
	if x != nil {
		return x.MaxDurationWhileIdle
	}
	return 0
}

func (x *EndOfLifeSetting) GetCloseWhenAllWriterDisconnected() bool {
	if x != nil {
		return x.CloseWhenAllWriterDisconnected
	}
	return false
}

type RoomSummary_HistorySummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActiveConnectionSize int32 `protobuf:"varint,4,opt,name=active_connection_size,json=activeConnectionSize,proto3" json:"active_connection_size,omitempty"`
	CommandSize          int64 `protobuf:"varint,5,opt,name=command_size,json=commandSize,proto3" json:"command_size,omitempty"`
	CommandMemorySize    int64 `protobuf:"varint,6,opt,name=command_memory_size,json=commandMemorySize,proto3" json:"command_memory_size,omitempty"`
	TickSize             int64 `protobuf:"varint,7,opt,name=tick_size,json=tickSize,proto3" json:"tick_size,omitempty"`
}

func (x *RoomSummary_HistorySummary) Reset() {
	*x = RoomSummary_HistorySummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_command_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomSummary_HistorySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomSummary_HistorySummary) ProtoMessage() {}

func (x *RoomSummary_HistorySummary) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_command_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomSummary_HistorySummary.ProtoReflect.Descriptor instead.
func (*RoomSummary_HistorySummary) Descriptor() ([]byte, []int) {
	return file_protobuf_command_proto_rawDescGZIP(), []int{12, 0}
}

func (x *RoomSummary_HistorySummary) GetActiveConnectionSize() int32 {
	if x != nil {
		return x.ActiveConnectionSize
	}
	return 0
}

func (x *RoomSummary_HistorySummary) GetCommandSize() int64 {
	if x != nil {
		return x.CommandSize
	}
	return 0
}

func (x *RoomSummary_HistorySummary) GetCommandMemorySize() int64 {
	if x != nil {
		return x.CommandMemorySize
	}
	return 0
}

func (x *RoomSummary_HistorySummary) GetTickSize() int64 {
	if x != nil {
		return x.TickSize
	}
	return 0
}

var File_protobuf_command_proto protoreflect.FileDescriptor

var file_protobuf_command_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x74, 0x6d, 0x70, 0x22, 0x34, 0x0a,
	0x08, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x12, 0x28, 0x0a, 0x08, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x74, 0x6d,
	0x70, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x73, 0x22, 0xb9, 0x01, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12,
	0x35, 0x0a, 0x0c, 0x74, 0x69, 0x63, 0x6b, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x6d, 0x70, 0x2e, 0x54, 0x69, 0x63, 0x6b,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x0b, 0x74, 0x69, 0x63, 0x6b, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x2f, 0x0a, 0x0a, 0x69, 0x64, 0x5f, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x6d, 0x70,
	0x2e, 0x49, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x09, 0x69, 0x64,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x3b, 0x0a, 0x0e, 0x77, 0x72, 0x69, 0x74, 0x65,
	0x72, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x74, 0x6d, 0x70, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x0d, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22,
	0x2e, 0x0a, 0x0b, 0x54, 0x69, 0x63, 0x6b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1f,
	0x0a, 0x0b, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x5f, 0x73, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0a, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x53, 0x65, 0x65, 0x64, 0x22,
	0x39, 0x0a, 0x09, 0x49, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x15, 0x0a, 0x06,
	0x6f, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x6c,
	0x64, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6e, 0x65, 0x77, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x65, 0x77, 0x49, 0x64, 0x22, 0x39, 0x0a, 0x0d, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x87, 0x01, 0x0a, 0x1b, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x41,
	0x6c, 0x6f, 0x6e, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x33, 0x0a, 0x0c, 0x72, 0x6f, 0x6f,
	0x6d, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x74, 0x6d, 0x70, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x52, 0x0b, 0x72, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x1f,
	0x0a, 0x0b, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x46, 0x69, 0x6c, 0x65, 0x22,
	0x8e, 0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x33,
	0x0a, 0x0c, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x6d, 0x70, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x0b, 0x72, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x12, 0x2b, 0x0a, 0x11, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x14, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2c, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72,
	0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f,
	0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x11, 0x0a, 0x0f, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3a, 0x0a,
	0x10, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x26, 0x0a, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x74, 0x6d, 0x70, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x79, 0x52, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x22, 0xf9, 0x02, 0x0a, 0x0b, 0x52, 0x6f,
	0x6f, 0x6d, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2a, 0x0a, 0x07, 0x73, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x6d, 0x70,
	0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x07, 0x73, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x2b, 0x0a, 0x11, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x10, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x48, 0x0a, 0x0f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x73, 0x75,
	0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x74, 0x6d,
	0x70, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x2e, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x0e, 0x68, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x1a, 0xb6, 0x01, 0x0a,
	0x0e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12,
	0x34, 0x0a, 0x16, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x14, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x2e, 0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x5f, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4d, 0x65,
	0x6d, 0x6f, 0x72, 0x79, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69, 0x63, 0x6b,
	0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x69, 0x63,
	0x6b, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x80, 0x01, 0x0a, 0x0c, 0x44, 0x65, 0x62, 0x75, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x01, 0x62, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x01, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x33, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x03, 0x69, 0x33, 0x32, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x36, 0x34, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x03, 0x69, 0x36, 0x34, 0x12, 0x14, 0x0a, 0x04, 0x6f, 0x69, 0x33, 0x32, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x04, 0x6f, 0x69, 0x33, 0x32, 0x12, 0x14, 0x0a, 0x04,
	0x6f, 0x69, 0x36, 0x34, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x04, 0x6f, 0x69,
	0x36, 0x34, 0x42, 0x04, 0x0a, 0x02, 0x6f, 0x6f, 0x22, 0x81, 0x01, 0x0a, 0x0d, 0x44, 0x65, 0x62,
	0x75, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x62, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x01, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x33, 0x32, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x69, 0x33, 0x32, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x36, 0x34, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x69, 0x36, 0x34, 0x12, 0x14, 0x0a, 0x04, 0x6f, 0x69,
	0x33, 0x32, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x04, 0x6f, 0x69, 0x33, 0x32,
	0x12, 0x14, 0x0a, 0x04, 0x6f, 0x69, 0x36, 0x34, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00,
	0x52, 0x04, 0x6f, 0x69, 0x36, 0x34, 0x42, 0x04, 0x0a, 0x02, 0x6f, 0x6f, 0x22, 0x6a, 0x0a, 0x0b,
	0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x24, 0x0a, 0x04, 0x74,
	0x69, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x6d, 0x70, 0x2e,
	0x54, 0x69, 0x63, 0x6b, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x04, 0x74, 0x69, 0x63,
	0x6b, 0x12, 0x35, 0x0a, 0x0b, 0x65, 0x6e, 0x64, 0x5f, 0x6f, 0x66, 0x5f, 0x6c, 0x69, 0x66, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x6d, 0x70, 0x2e, 0x45, 0x6e, 0x64,
	0x4f, 0x66, 0x4c, 0x69, 0x66, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x09, 0x65,
	0x6e, 0x64, 0x4f, 0x66, 0x4c, 0x69, 0x66, 0x65, 0x22, 0x7b, 0x0a, 0x0b, 0x54, 0x69, 0x63, 0x6b,
	0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x33, 0x0a, 0x15, 0x66,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x6e, 0x61, 0x6e, 0x6f, 0x73, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x14, 0x66, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x6e, 0x63, 0x79, 0x4e, 0x61, 0x6e, 0x6f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73,
	0x12, 0x23, 0x0a, 0x0d, 0x61, 0x6c, 0x77, 0x61, 0x79, 0x73, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x61, 0x6c, 0x77, 0x61, 0x79, 0x73, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x22, 0xb8, 0x01, 0x0a, 0x10, 0x45, 0x6e, 0x64, 0x4f, 0x66, 0x4c,
	0x69, 0x66, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x61,
	0x78, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0b, 0x6d, 0x61, 0x78, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x35, 0x0a,
	0x17, 0x6d, 0x61, 0x78, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x77, 0x68,
	0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x14,
	0x6d, 0x61, 0x78, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x57, 0x68, 0x69, 0x6c, 0x65,
	0x49, 0x64, 0x6c, 0x65, 0x12, 0x4a, 0x0a, 0x22, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x77, 0x68,
	0x65, 0x6e, 0x5f, 0x61, 0x6c, 0x6c, 0x5f, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x5f, 0x64, 0x69,
	0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x1e, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x57, 0x68, 0x65, 0x6e, 0x41, 0x6c, 0x6c, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x72, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x32, 0xca, 0x01, 0x0a, 0x0b, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x39, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x14, 0x2e, 0x74,
	0x6d, 0x70, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x15, 0x2e, 0x74, 0x6d, 0x70, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x6f,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0a, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x16, 0x2e, 0x74, 0x6d, 0x70, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x17, 0x2e, 0x74, 0x6d, 0x70, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f,
	0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0a,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x16, 0x2e, 0x74, 0x6d, 0x70,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x17, 0x2e, 0x74, 0x6d, 0x70, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0b, 0x5a,
	0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protobuf_command_proto_rawDescOnce sync.Once
	file_protobuf_command_proto_rawDescData = file_protobuf_command_proto_rawDesc
)

func file_protobuf_command_proto_rawDescGZIP() []byte {
	file_protobuf_command_proto_rawDescOnce.Do(func() {
		file_protobuf_command_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_command_proto_rawDescData)
	})
	return file_protobuf_command_proto_rawDescData
}

var file_protobuf_command_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_protobuf_command_proto_goTypes = []interface{}{
	(*Commands)(nil),                    // 0: tmp.Commands
	(*Command)(nil),                     // 1: tmp.Command
	(*TickCommand)(nil),                 // 2: tmp.TickCommand
	(*IdCommand)(nil),                   // 3: tmp.IdCommand
	(*WriterCommand)(nil),               // 4: tmp.WriterCommand
	(*StandAloneRoomServerSetting)(nil), // 5: tmp.StandAloneRoomServerSetting
	(*CreateRoomRequest)(nil),           // 6: tmp.CreateRoomRequest
	(*CreateRoomResponse)(nil),          // 7: tmp.CreateRoomResponse
	(*DeleteRoomRequest)(nil),           // 8: tmp.DeleteRoomRequest
	(*DeleteRoomResponse)(nil),          // 9: tmp.DeleteRoomResponse
	(*ListRoomRequest)(nil),             // 10: tmp.ListRoomRequest
	(*ListRoomResponse)(nil),            // 11: tmp.ListRoomResponse
	(*RoomSummary)(nil),                 // 12: tmp.RoomSummary
	(*DebugRequest)(nil),                // 13: tmp.DebugRequest
	(*DebugResponse)(nil),               // 14: tmp.DebugResponse
	(*RoomSetting)(nil),                 // 15: tmp.RoomSetting
	(*TickSetting)(nil),                 // 16: tmp.TickSetting
	(*EndOfLifeSetting)(nil),            // 17: tmp.EndOfLifeSetting
	(*RoomSummary_HistorySummary)(nil),  // 18: tmp.RoomSummary.HistorySummary
}
var file_protobuf_command_proto_depIdxs = []int32{
	1,  // 0: tmp.Commands.commands:type_name -> tmp.Command
	2,  // 1: tmp.Command.tick_command:type_name -> tmp.TickCommand
	3,  // 2: tmp.Command.id_command:type_name -> tmp.IdCommand
	4,  // 3: tmp.Command.writer_command:type_name -> tmp.WriterCommand
	15, // 4: tmp.StandAloneRoomServerSetting.room_setting:type_name -> tmp.RoomSetting
	15, // 5: tmp.CreateRoomRequest.room_setting:type_name -> tmp.RoomSetting
	12, // 6: tmp.ListRoomResponse.rooms:type_name -> tmp.RoomSummary
	15, // 7: tmp.RoomSummary.setting:type_name -> tmp.RoomSetting
	18, // 8: tmp.RoomSummary.history_summary:type_name -> tmp.RoomSummary.HistorySummary
	16, // 9: tmp.RoomSetting.tick:type_name -> tmp.TickSetting
	17, // 10: tmp.RoomSetting.end_of_life:type_name -> tmp.EndOfLifeSetting
	10, // 11: tmp.RoomService.ListRoom:input_type -> tmp.ListRoomRequest
	6,  // 12: tmp.RoomService.CreateRoom:input_type -> tmp.CreateRoomRequest
	8,  // 13: tmp.RoomService.DeleteRoom:input_type -> tmp.DeleteRoomRequest
	11, // 14: tmp.RoomService.ListRoom:output_type -> tmp.ListRoomResponse
	7,  // 15: tmp.RoomService.CreateRoom:output_type -> tmp.CreateRoomResponse
	9,  // 16: tmp.RoomService.DeleteRoom:output_type -> tmp.DeleteRoomResponse
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_protobuf_command_proto_init() }
func file_protobuf_command_proto_init() {
	if File_protobuf_command_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_command_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Commands); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_command_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_command_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TickCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_command_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_command_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriterCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_command_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StandAloneRoomServerSetting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_command_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_command_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_command_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_command_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_command_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_command_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_command_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_command_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DebugRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_command_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DebugResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_command_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomSetting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_command_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TickSetting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_command_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndOfLifeSetting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_command_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomSummary_HistorySummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protobuf_command_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Command_TickCommand)(nil),
		(*Command_IdCommand)(nil),
		(*Command_WriterCommand)(nil),
	}
	file_protobuf_command_proto_msgTypes[13].OneofWrappers = []interface{}{
		(*DebugRequest_Oi32)(nil),
		(*DebugRequest_Oi64)(nil),
	}
	file_protobuf_command_proto_msgTypes[14].OneofWrappers = []interface{}{
		(*DebugResponse_Oi32)(nil),
		(*DebugResponse_Oi64)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_command_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_command_proto_goTypes,
		DependencyIndexes: file_protobuf_command_proto_depIdxs,
		MessageInfos:      file_protobuf_command_proto_msgTypes,
	}.Build()
	File_protobuf_command_proto = out.File
	file_protobuf_command_proto_rawDesc = nil
	file_protobuf_command_proto_goTypes = nil
	file_protobuf_command_proto_depIdxs = nil
}
