FROM golang:1
ARG repo_slug=lijiaqigreat/personal_server
ENV BUILD_DIR=$GOPATH/src/github.com/$repo_slug

RUN apt-get update && apt-get install unzip

RUN mkdir -p $BUILD_DIR
RUN ln -s $BUILD_DIR /build
WORKDIR $BUILD_DIR

ADD install.sh .
RUN sh install.sh
RUN go get -u github.com/golang/protobuf/protoc-gen-go
RUN go get -u github.com/twitchtv/twirp/protoc-gen-twirp

ADD . .
RUN make proto
RUN go get -t ./...
CMD ["go", "test"]
